### ISSUE TITLE
Frontend boilerplate bootstrap

### ISSUE THREAD

**Issue by AkshatRamanathan** [yashksaini-coder/BookStream#10]
Tools to include -

1. Vite
2. Typescript
3. Tailwind
4. React

**Comment by AkshatRamanathan** [comment]
Will also work on the CONTRIBUTION.md file as discussed

**Comment by AkshatRamanathan** [comment]
Raised PR#15. Please verify and approve @yashksaini-coder

**Comment by yashksaini-coder** [comment]
Sure I will check and merge the PR soon.
