### ISSUE TITLE
Set up files for front end

### ISSUE THREAD

**Issue by HYnam** [yashksaini-coder/BookStream#11]
Set up file structure for front end development with Typescript, Tailwind, React packages installed

**Comment by AkshatRamanathan** [comment]
I have already created this issue. @yashksaini-coder please confirm and close

**Comment by HYnam** [comment]
Oh... sorry!!

**Comment by yashksaini-coder** [comment]
> [!NOTE]
> The Front-End setup was already created & assigned to @AkshatRamanathan But don't worry I will be providing a list after the Front-End is setup by Akshat. once the basic Front-end layer is setup. Both of you can get started on working the different tasks.

**Comment by AkshatRamanathan** [comment]
Sounds good. I’ll do the boilerplate setup today and then the other dev can begin their work

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
