### ISSUE TITLE
Creating Login / Signup Frontend

### ISSUE THREAD

**Issue by ParasY1724** [yashksaini-coder/BookStream#21]
**Desctiption:**
- Creating Pages for Login and Signup
- Set up API routes in Next.js to handle backend functionality (user authentication, book management, etc.) 
- Implement responsive design by adjusting the TailwindCSS classes for different screen sizes.

**Comment by yashksaini-coder** [comment]
> Please assign this task to me under gssoc-extd24.

sure go ahead @ParasY1724

**Comment by yashksaini-coder** [comment]
make sure to create another branch when you contribute
