### ISSUE TITLE
Integration of Frontend and Backend Login / SignUp endpoints

### ISSUE THREAD

**Issue by ParasY1724** [yashksaini-coder/BookStream#25]
**Description:**
Integrating Backend endpoints :
```
/api/auth/login => login
/api/auth/register => register
```

**Comment by ParasY1724** [comment]
Assign this task to me , i have implemented this with my PR #26 under gssoc-extd24

**Comment by yashksaini-coder** [comment]
By the way you should see this #24 new updates here
