### ISSUE TITLE
Proposal for a contributing.md file 

### ISSUE THREAD

**Issue by nishakp3005** [yashksaini-coder/BookStream#28]
This readme includes these points : 
- Code of Conduct: Behavior guidelines.
- Setup: Local installation steps.
- Contributing: Bug reports, features, code.
- Branches: Branching rules.
- Style Guide: Code formatting rules.
- Commits: Message format.
- Testing: Running tests.
- Pull Requests: Submission guidelines.
- Reviews: PR review process.
- License: Contributor legal info.

kindly assign me this issue

**Comment by yashksaini-coder** [comment]
Hi @nishakp3005 Thank you for raising a detailed issue however this project is no longer in the gssoc or wob

**Comment by nishakp3005** [comment]
nvm, I can still help you with it!

**Comment by yashksaini-coder** [comment]
> nvm, I can still help you with it!

okh I appreciate it.
