### ISSUE TITLE
Add Automated 'Greetings' workflow

### ISSUE THREAD

**Issue by harish08102004** [yashksaini-coder/BookStream#29]
I propose to create a Github workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greetings will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open - source project. We aim to respond or assign your issue as soon as possible.

Hey @yashksaini-coder I can work on this.

**Comment by yashksaini-coder** [comment]
first read the discussions

**Comment by harish08102004** [comment]
No issues I want to learn I can still do it.

**Comment by yashksaini-coder** [comment]
go ahead

**Comment by yashksaini-coder** [comment]
Are you still contributing to this issue @harish08102004
