### ISSUE TITLE
 Create a Dockerfile for the Project

### ISSUE THREAD

**Issue by rishyym0927** [yashksaini-coder/BookStream#34]
**Description:**
We need to create a Dockerfile to containerize the project for easier deployment and consistency across different environments. The Dockerfile should:
- Set up the appropriate base image (e.g., `node:alpine` or `python:slim` depending on the tech stack).
- Install necessary dependencies.
- Copy the source code into the container.
- Expose the required port (if applicable).
- Define the entry point or command to run the application.

**Level:** GSSOC-EXT,  Level 3

**Assigned To:** @mention (or "To Be Assigned")

**Comment by yashksaini-coder** [comment]
Hi @rishyym0927 this project is not in gssoc-ext, but is acceptable in hacktoberfest I guess.
