### ISSUE TITLE
Upload .env.example, Remove .env, and Update .gitignore for Smoother Development

### ISSUE THREAD

**Issue by rishyym0927** [yashksaini-coder/BookStream#35]
**Description:**
To ensure smoother collaboration and deployment, we need to make the following changes:
1. **Upload a `.env.example` file:**  
   This file should include all the necessary environment variables without any sensitive information (e.g., API keys, database credentials). It will serve as a reference for other developers to create their own `.env` files.
   
2. **Remove the `.env` file from the repository:**  
   Sensitive information should not be committed to version control. We'll remove the existing `.env` file from the repository to ensure it isn't exposed.

3. **Update `.gitignore`:**  
   Add the `.env` file to `.gitignore` to prevent it from being accidentally committed in the future.

**Level:** GSSOC-EXT Level 3

**Comment by Suraj-kumar00** [comment]
@yashksaini-coder But this issue is not completed, why did you close that?

**Comment by yashksaini-coder** [comment]
@Suraj-kumar00 i didn't close this issue if you see clearly

**Comment by Suraj-kumar00** [comment]
My bad, I saw it was close my @rishyym0927 but what I meant was it's not completed so If you want I can raise the PR first about this one!
