### ISSUE TITLE
Install packages? 

### ISSUE THREAD

**Issue by HYnam** [yashksaini-coder/BookStream#4]
Do I need to install new package to run this application? Or just `npm start`
If yes, would be nice to include packages that need to be installed in the readme :)

**Comment by yashksaini-coder** [comment]
Yes do install the packages.

**Comment by HYnam** [comment]
I would like to contribute for the frontend. Do you have any design that I can implement directly?

**Comment by yashksaini-coder** [comment]
The design I want to implement is something like this [Link](https://github.com/mdalmamunit427/book-inventory-starter-files)

**Comment by HYnam** [comment]
Thanks, I'll have a look
