### ISSUE TITLE
User Dashboard

### ISSUE THREAD

**Issue by yashksaini-coder** [yashksaini-coder/BookStream#41]
Design a UI/UX friendly user dashboard to show all the details of the books in the cart, purchased, at what price, or what date.

Use external libraries for designing the dashboard, such as framer-motion, aceternity UI, Magic UI etc

**Comment by anantrajjj** [comment]
can this issue be assigned to me please? thanks.

**Comment by yashksaini-coder** [comment]
assigned, before raising PR share screenshots or small mp4 to showcase the dashboard

**Comment by anantrajjj** [comment]
https://github.com/user-attachments/assets/86e76021-18c2-47db-9dcc-7a40c10315e4

is this alright?
