### ISSUE TITLE
Need of Dockerfile for Project Containerization and Deployment.

### ISSUE THREAD

**Issue by Suraj-kumar00** [yashksaini-coder/BookStream#48]
### Description:
It is frustrating to setup the local development environment for everyone so...

We need to containerize our project for easier deployment and consistency across various environments. The Dockerfile should include the necessary configurations to build and run our application in a Docker container.

I would like to work on this issue as I'm proficient in `Cloud/DevOps` practices. I can:
1. Dockerize the project. 
2. Dockerize the project with `minimal docker image`.
3. Can Create a workflow to `build` and `push` the docker images to the `DockerHub Account` but for this I will need the credentials of your dockerhub account to push to docker image on your account.

Please assign this issue to me so that I can work on it.

**Comment by yashksaini-coder** [comment]
@Suraj-kumar00 sure go ahead.

**Comment by Suraj-kumar00** [comment]
> @Suraj-kumar00 sure go ahead.

Will update soon.

**Comment by Suraj-kumar00** [comment]
Hey @yashksaini-coder, how have you been?

I have doubt about your directory structure, it's confusing because this is a nextjs directory structure and you have created `backend` directory as in the nextjs directory instead of creating is seperate like
1. `frontend`: this frontend will contain all the nextjs directory structure
2. `backend` this backend will contain the backend structure

And about the keys I have to setup locally on my own.

So could you please explain me is there are frontend and backend directory structure you have followed of explain me what it is because according to that I'll be dockerizing this project.

**Comment by yashksaini-coder** [comment]
> Hey @yashksaini-coder, how have you been?
> 
> I have doubt about your directory structure, it's confusing because this is a nextjs directory structure and you have created `backend` directory as in the nextjs directory instead of creating is seperate like
> 
> 1. `frontend`: this frontend will contain all the nextjs directory structure
> 2. `backend` this backend will contain the backend structure
> 
> And about the keys I have to setup locally on my own.
> 
> So could you please explain me is there are frontend and backend directory structure you have followed of explain me what it is because according to that I'll be dockerizing this project.

okh, if you can then raise the issue to restructure the codebase but make sure no other functions are affected during the process @Suraj-kumar00

**Comment by Suraj-kumar00** [comment]
Hey @yashksaini-coder can you please provide me the demo video of the project because I haven't found the deployed link as I'm facing issues on the local development setup and I have to create secrets keys as you mentioned in the README file.

**Comment by Suraj-kumar00** [comment]
Hi @yashksaini-coder I need your help about how to run the backend and running the `npm run dev`.

**Comment by Suraj-kumar00** [comment]
> Hi @yashksaini-coder I need your help about how to run the backend and running the `npm run dev`.

Hi @yashksaini-coder, please guide me about that.

**Comment by yashksaini-coder** [comment]
hi @Suraj-kumar00 i was thinking is there a need of dockerizing this application

**Comment by yashksaini-coder** [comment]
I am also occupied with the hacktoberfest event.
