### ISSUE TITLE
feature[ ] i want to add login error makes more informative

### ISSUE THREAD

**Issue by nishant4500** [yashksaini-coder/BookStream#49]
Improve Error Handling: Enhance the error handling in the handleSubmit function to check for specific HTTP status codes (like 400, 401, 500) and provide informative error messages to users.
Validation:

Client-Side Validation: Implement basic client-side validation for the email format and password strength to improve user experience.
Accessibility Improvements:

Button Accessibility: Ensure the button for toggling password visibility has appropriate accessibility attributes (like aria-label) for screen readers.
Styling:

Tailwind CSS: Consider extracting repeated styles into reusable components or using Tailwind's @apply directive for better maintainability.

**Comment by nishant4500** [comment]
can you look into this and mark the level and gssoc ext

**Comment by nishant4500** [comment]
can you add this gssoc-ext and level

**Comment by yashksaini-coder** [comment]
> can you add this gssoc-ext and level @yashksaini-coder

its not a part of gssoc

**Comment by nishant4500** [comment]
![image](https://github.com/user-attachments/assets/10c2db48-ab8f-489c-83df-1829ccc08b45)
so how this

**Comment by yashksaini-coder** [comment]
> ![image](https://private-user-images.githubusercontent.com/135944619/376031402-10c2db48-ab8f-489c-83df-1829ccc08b45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MjE5NTYsIm5iZiI6MTcyODgyMTY1NiwicGF0aCI6Ii8xMzU5NDQ2MTkvMzc2MDMxNDAyLTEwYzJkYjQ4LWFiOGYtNDg5Yy04M2RmLTE4MjljY2MwOGI0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMjE0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDFkZDZkNmRiMzUxMTAzNjA5MjFiNDg5NGQwMzAyMTA0MGM0Y2Q2OTUxOTQwYmI3MjdkZTAwNjNmODA2ZDYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Cp8LNUZDN19WSVOAxC7OCBytpxM7BQWRmdhDoreYDVY)
> 
> ## so how this is marked gssoc ext

At first I was PA but due to multiple roles I chose contributor only, now that was the first one which I nullified, I let program manager know to remove all the gssoc PR of my project

Hacktoberfest still counts.
