### ISSUE TITLE
ADD Future Enhancements / Roadmap on the README file

### ISSUE THREAD

**Issue by alo7lika** [yashksaini-coder/BookStream#59]
Adding a Future Enhancements / Roadmap section to the README is important for several reasons:

Clarity on Project Direction: A roadmap provides contributors and users with a clear understanding of the long-term vision and future goals of the project. This transparency helps align everyone’s efforts towards the same objectives.

Encourages Contributions: By showcasing planned features or improvements, a roadmap can inspire developers to contribute by picking up tasks that align with their skills or interests. It helps developers know where their contributions would be most valuable.

Community Engagement: Users and contributors can get excited about upcoming features. It allows them to provide feedback, suggest features, or help prioritize tasks, fostering a more engaged community.

Organization and Focus: A roadmap provides structure to the development process by breaking down future features into achievable milestones. This helps keep the development process organized, especially in an open-source setting where multiple contributors are working together.

Trust and Commitment: A well-laid-out plan shows commitment from the maintainers, making users and potential contributors feel confident that the project will continue to be developed and supported in the future.

Overall, a Future Enhancements / Roadmap section helps manage expectations and increases the likelihood of attracting active participation and feedback from the community.

ADD GSSOC EXT 24 AND HACKTOBERFEST LABELS
ASSIGN ME THIS WORK @yashksaini-coder 
THANK YOU!

**Comment by yashksaini-coder** [comment]
Approach is good, while you are at it, can you also add hacktoberfest banner & improve the README overview

**Comment by alo7lika** [comment]
> Approach is good, while you are at it, can you also add hacktoberfest banner & improve the README overview

Sure, I insist then you assign me the task under level 3 if possible.
THANK YOU!

**Comment by yashksaini-coder** [comment]
> > Approach is good, while you are at it, can you also add hacktoberfest banner & improve the README overview
> 
> Sure, I insist then you assign me the task under level 3 if possible. THANK YOU!

Already did @alo7lika, but in case you didn't see the #24 discussion, this project is no longer a part of `GSSOC` or `WoB`

However it is accepted by the Hacktoberfest guidelines so any PR accepted here will count towards your hacktoberfest PR goal.

**Comment by alo7lika** [comment]
> > > Approach is good, while you are at it, can you also add hacktoberfest banner & improve the README overview
> > 
> > 
> > Sure, I insist then you assign me the task under level 3 if possible. THANK YOU!
> 
> Already did @alo7lika, but in case you didn't see the #24 discussion, this project is no longer a part of `GSSOC` or `WoB`
> 
> However it is accepted by the Hacktoberfest guidelines so any PR accepted here will count towards your hacktoberfest PR goal.

I was talking about the "LEVEL" (1/2/3) that has to be assigned to get points.
So I asked you to assign the LEVEL 3 Label .

**Comment by yashksaini-coder** [comment]
> > > > Approach is good, while you are at it, can you also add hacktoberfest banner & improve the README overview
> > > 
> > > 
> > > Sure, I insist then you assign me the task under level 3 if possible. THANK YOU!
> > 
> > 
> > Already did @alo7lika, but in case you didn't see the #24 discussion, this project is no longer a part of `GSSOC` or `WoB`
> > However it is accepted by the Hacktoberfest guidelines so any PR accepted here will count towards your hacktoberfest PR goal.
> 
> I was talking about the "LEVEL" (1/2/3) that has to be assigned to get points. So I asked you to assign the LEVEL 3 Label .


I know what you were mentioning, but this project has been removed from the GSSOC-ext
